apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job
spec:
  completions: 2
  parallelism: 2
  template:
    metadata:
      labels: 
        app: batch-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: pi 
        image: figent/batch-job